FROM ubuntu 
LABEL description="Container for use with Visual Studio" 
RUN apt-get update && apt-get install -y g++ rsync zip openssh-server make
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip cmake
RUN apt-get install -y gdb gdbserver
RUN pip3 install conan 
RUN mkdir -p /var/run/sshd
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \ 
   ssh-keygen -A 

EXPOSE 22